# Generated by Django 5.2.3 on 2025-06-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_is_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
